// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/upload.js";
import * as $1 from "./routes/index.jsx";
import * as $$0 from "./islands/Form.jsx";

const manifest = {
  routes: {
    "./routes/api/upload.js": $0,
    "./routes/index.jsx": $1,
  },
  islands: {
    "./islands/Form.jsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
